set_wifi:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: marstek_modbus
          multiple: true
    ssid:
      required: true
      example: "MyNetwork"
      selector:
        text:
    password:
      required: false
      example: "my-wifi-password"
      selector:
        text:
          type: password
